### ISSUE TITLE
i is not defined

### ISSUE THREAD

**Issue by zachjonesnoel** [jaw187/node-traceroute#15]
When running sample snippet to trace route www.google.com

```
traceroute = require('traceroute');
traceroute.trace('google.com', function (err,hops) {
  if (!err) console.log(hops);
});
```
Getting this error. 
```
\node_modules\traceroute\traceroute.js:114
        lines.splice(0,i);
                       ^

ReferenceError: i is not defined
    at Object.internals.parseOutput (..\node_modules\traceroute\traceroute.js:114:24)
    at ..\node_modules\traceroute\traceroute.js:35:39
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by jaw187** [comment]
what version was this with?

**Comment by zachjonesnoel** [comment]
Version : "^1.0.0"
