### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by revisionfour** [jaw187/node-traceroute#9]
You need to update npm to the newest version in this repo. Otherwise you get

trace.on('hop', (hop) => {
     ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/developmentmastery/Repos/testing-traceroute/index.js:5:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3

When you try to use stream.

**Comment by weissmag** [comment]
+10
